// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths {
    public static var radar: Radar {
        Radar(path: "/v1/radar")
    }

    public struct Radar {
        /// Path: `/v1/radar`
        public let path: String
    }
}
