// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths {
    public static var terminal: Terminal {
        Terminal(path: "/v1/terminal")
    }

    public struct Terminal {
        /// Path: `/v1/terminal`
        public let path: String
    }
}
