// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.TestHelpers {
    public var customers: Customers {
        Customers(path: path + "/customers")
    }

    public struct Customers {
        /// Path: `/v1/test_helpers/customers`
        public let path: String
    }
}
