// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.TestHelpers.Issuing.Cards.WithCard {
    public var shipping: Shipping {
        Shipping(path: path + "/shipping")
    }

    public struct Shipping {
        /// Path: `/v1/test_helpers/issuing/cards/{card}/shipping`
        public let path: String
    }
}
