// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.Invoices.WithInvoice {
    public var pay: Pay {
        Pay(path: path + "/pay")
    }

    public struct Pay {
        /// Path: `/v1/invoices/{invoice}/pay`
        public let path: String

        /// <p>Stripe automatically creates and then attempts to collect payment on invoices for customers on subscriptions according to your <a href="https://dashboard.stripe.com/account/billing/automatic">subscriptions settings</a>. However, if you’d like to attempt payment on an invoice out of the normal collection schedule or for some other reason, you can do so.</p>
        public func post(_ body: PostRequest? = nil) -> Request<StripeKit.Invoice> {
            Request(method: "POST", url: path, body: body.map(URLQueryEncoder.encode)?.percentEncodedQuery, id: "PostInvoicesInvoicePay")
        }

        public struct PostRequest: Encodable {
            /// Specifies which fields in the response should be expanded.
            public var expand: [String]?
            /// In cases where the source used to pay the invoice has insufficient funds, passing `forgive=true` controls whether a charge should be attempted for the full amount available on the source, up to the amount to fully pay the invoice. This effectively forgives the difference between the amount available on the source and the amount due. 
            /// 
            /// Passing `forgive=false` will fail the charge if the source hasn't been pre-funded with the right amount. An example for this case is with ACH Credit Transfers and wires: if the amount wired is less than the amount due by a small amount, you might want to forgive the difference. Defaults to `false`.
            public var isForgive: Bool?
            /// ID of the mandate to be used for this invoice. It must correspond to the payment method used to pay the invoice, including the payment_method param or the invoice's default_payment_method or default_source, if set.
            public var mandate: String?
            /// Indicates if a customer is on or off-session while an invoice payment is attempted. Defaults to `true` (off-session).
            public var isOffSession: Bool?
            /// Boolean representing whether an invoice is paid outside of Stripe. This will result in no charge being made. Defaults to `false`.
            public var isPaidOutOfBand: Bool?
            /// A PaymentMethod to be charged. The PaymentMethod must be the ID of a PaymentMethod belonging to the customer associated with the invoice being paid.
            public var paymentMethod: String?
            /// A payment source to be charged. The source must be the ID of a source belonging to the customer associated with the invoice being paid.
            public var source: String?

            public init(expand: [String]? = nil, isForgive: Bool? = nil, mandate: String? = nil, isOffSession: Bool? = nil, isPaidOutOfBand: Bool? = nil, paymentMethod: String? = nil, source: String? = nil) {
                self.expand = expand
                self.isForgive = isForgive
                self.mandate = mandate
                self.isOffSession = isOffSession
                self.isPaidOutOfBand = isPaidOutOfBand
                self.paymentMethod = paymentMethod
                self.source = source
            }

            public var asQuery: [(String, String?)] {
                let encoder = URLQueryEncoder()
                encoder.encode(expand, forKey: "expand")
                encoder.encode(isForgive, forKey: "forgive")
                encoder.encode(mandate, forKey: "mandate")
                encoder.encode(isOffSession, forKey: "off_session")
                encoder.encode(isPaidOutOfBand, forKey: "paid_out_of_band")
                encoder.encode(paymentMethod, forKey: "payment_method")
                encoder.encode(source, forKey: "source")
                return encoder.items
            }
        }
    }
}
