// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths {
    public static var financialConnections: FinancialConnections {
        FinancialConnections(path: "/v1/financial_connections")
    }

    public struct FinancialConnections {
        /// Path: `/v1/financial_connections`
        public let path: String
    }
}
