// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import Get
import URLQueryEncoder

extension Paths.LinkedAccounts {
    public func account(_ account: String) -> WithAccount {
        WithAccount(path: "\(path)/\(account)")
    }

    public struct WithAccount {
        /// Path: `/v1/linked_accounts/{account}`
        public let path: String

        /// <p>Retrieves the details of an Financial Connections <code>Account</code>.</p>
        public func get(expand: [String]? = nil) -> Request<StripeKit.FinancialConnectionsAccount> {
            Request(method: "GET", url: path, query: makeGetQuery(expand), id: "GetLinkedAccountsAccount")
        }

        private func makeGetQuery(_ expand: [String]?) -> [(String, String?)] {
            let encoder = URLQueryEncoder()
            encoder.encode(expand, forKey: "expand", isDeepObject: true)
            return encoder.items
        }
    }
}
