// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

/// Account Links are the means by which a Connect platform grants a connected account permission to access
/// Stripe-hosted applications, such as Connect Onboarding.
/// 
/// Related guide: [Connect Onboarding](https://stripe.com/docs/connect/connect-onboarding).
public struct AccountLink: Codable {
    /// Time at which the object was created. Measured in seconds since the Unix epoch.
    public var created: Int
    /// The timestamp at which this account link will expire.
    public var expiresAt: Int
    /// String representing the object's type. Objects of the same type share the same value.
    public var object: Object
    /// The URL for the account link.
    public var url: String

    /// String representing the object's type. Objects of the same type share the same value.
    public enum Object: String, Codable, CaseIterable {
        case accountLink = "account_link"
    }

    public init(created: Int, expiresAt: Int, object: Object, url: String) {
        self.created = created
        self.expiresAt = expiresAt
        self.object = object
        self.url = url
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.created = try values.decode(Int.self, forKey: "created")
        self.expiresAt = try values.decode(Int.self, forKey: "expires_at")
        self.object = try values.decode(Object.self, forKey: "object")
        self.url = try values.decode(String.self, forKey: "url")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(created, forKey: "created")
        try values.encode(expiresAt, forKey: "expires_at")
        try values.encode(object, forKey: "object")
        try values.encode(url, forKey: "url")
    }
}
