// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct BalanceAmountBySourceType: Codable {
    /// Amount for bank account.
    public var bankAccount: Int?
    /// Amount for card.
    public var card: Int?
    /// Amount for FPX.
    public var fpx: Int?

    public init(bankAccount: Int? = nil, card: Int? = nil, fpx: Int? = nil) {
        self.bankAccount = bankAccount
        self.card = card
        self.fpx = fpx
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.bankAccount = try values.decodeIfPresent(Int.self, forKey: "bank_account")
        self.card = try values.decodeIfPresent(Int.self, forKey: "card")
        self.fpx = try values.decodeIfPresent(Int.self, forKey: "fpx")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(bankAccount, forKey: "bank_account")
        try values.encodeIfPresent(card, forKey: "card")
        try values.encodeIfPresent(fpx, forKey: "fpx")
    }
}
