// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct CountrySpecVerificationFields: Codable {
    /// CountrySpecVerificationFieldDetails
    public var company: CountrySpecVerificationFieldDetails
    /// CountrySpecVerificationFieldDetails
    public var individual: CountrySpecVerificationFieldDetails

    public init(company: CountrySpecVerificationFieldDetails, individual: CountrySpecVerificationFieldDetails) {
        self.company = company
        self.individual = individual
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.company = try values.decode(CountrySpecVerificationFieldDetails.self, forKey: "company")
        self.individual = try values.decode(CountrySpecVerificationFieldDetails.self, forKey: "individual")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(company, forKey: "company")
        try values.encode(individual, forKey: "individual")
    }
}
