// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct CustomerTaxLocation: Codable {
    /// The customer's country as identified by Stripe Tax.
    public var country: String
    /// The data source used to infer the customer's location.
    public var source: Source
    /// The customer's state, county, province, or region as identified by Stripe Tax.
    public var state: String?

    /// The data source used to infer the customer's location.
    public enum Source: String, Codable, CaseIterable {
        case billingAddress = "billing_address"
        case ipAddress = "ip_address"
        case paymentMethod = "payment_method"
        case shippingDestination = "shipping_destination"
    }

    public init(country: String, source: Source, state: String? = nil) {
        self.country = country
        self.source = source
        self.state = state
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.country = try values.decode(String.self, forKey: "country")
        self.source = try values.decode(Source.self, forKey: "source")
        self.state = try values.decodeIfPresent(String.self, forKey: "state")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(country, forKey: "country")
        try values.encode(source, forKey: "source")
        try values.encodeIfPresent(state, forKey: "state")
    }
}
