// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

/// Invoice_payment_method_options_acss_debit
public struct InvoicePaymentMethodOptionsAcssDebit: Codable {
    /// Invoice_payment_method_options_acss_debit_mandate_options
    public var mandateOptions: InvoicePaymentMethodOptionsAcssDebitMandateOptions?
    /// Bank account verification method.
    public var verificationMethod: VerificationMethod?

    /// Bank account verification method.
    public enum VerificationMethod: String, Codable, CaseIterable {
        case automatic
        case instant
        case microdeposits
    }

    public init(mandateOptions: InvoicePaymentMethodOptionsAcssDebitMandateOptions? = nil, verificationMethod: VerificationMethod? = nil) {
        self.mandateOptions = mandateOptions
        self.verificationMethod = verificationMethod
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.mandateOptions = try values.decodeIfPresent(InvoicePaymentMethodOptionsAcssDebitMandateOptions.self, forKey: "mandate_options")
        self.verificationMethod = try values.decodeIfPresent(VerificationMethod.self, forKey: "verification_method")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(mandateOptions, forKey: "mandate_options")
        try values.encodeIfPresent(verificationMethod, forKey: "verification_method")
    }
}
