// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct InvoiceThresholdReason: Codable {
    /// The total invoice amount threshold boundary if it triggered the threshold invoice.
    public var amountGte: Int?
    /// Indicates which line items triggered a threshold invoice.
    public var itemReasons: [InvoiceItemThresholdReason]

    public init(amountGte: Int? = nil, itemReasons: [InvoiceItemThresholdReason]) {
        self.amountGte = amountGte
        self.itemReasons = itemReasons
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.amountGte = try values.decodeIfPresent(Int.self, forKey: "amount_gte")
        self.itemReasons = try values.decode([InvoiceItemThresholdReason].self, forKey: "item_reasons")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(amountGte, forKey: "amount_gte")
        try values.encode(itemReasons, forKey: "item_reasons")
    }
}
