// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct IssuingCardholderIndividual: Codable {
    /// The date of birth of this cardholder.
    public var dob: IssuingCardholderIndividualDob?
    /// The first name of this cardholder.
    public var firstName: String
    /// The last name of this cardholder.
    public var lastName: String
    /// Government-issued ID document for this cardholder.
    public var verification: IssuingCardholderVerification?

    public init(dob: IssuingCardholderIndividualDob? = nil, firstName: String, lastName: String, verification: IssuingCardholderVerification? = nil) {
        self.dob = dob
        self.firstName = firstName
        self.lastName = lastName
        self.verification = verification
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.dob = try values.decodeIfPresent(IssuingCardholderIndividualDob.self, forKey: "dob")
        self.firstName = try values.decode(String.self, forKey: "first_name")
        self.lastName = try values.decode(String.self, forKey: "last_name")
        self.verification = try values.decodeIfPresent(IssuingCardholderVerification.self, forKey: "verification")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(dob, forKey: "dob")
        try values.encode(firstName, forKey: "first_name")
        try values.encode(lastName, forKey: "last_name")
        try values.encodeIfPresent(verification, forKey: "verification")
    }
}
