// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

/// Linked_account_options_us_bank_account
public struct LinkedAccountOptionsUsBankAccount: Codable {
    /// The list of permissions to request. The `payment_method` permission must be included.
    public var permissions: [Permission]?
    /// For webview integrations only. Upon completing OAuth login in the native browser, the user will be redirected to this URL to return to your app.
    public var returnURL: String?

    public enum Permission: String, Codable, CaseIterable {
        case balances
        case ownership
        case paymentMethod = "payment_method"
        case transactions
    }

    public init(permissions: [Permission]? = nil, returnURL: String? = nil) {
        self.permissions = permissions
        self.returnURL = returnURL
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.permissions = try values.decodeIfPresent([Permission].self, forKey: "permissions")
        self.returnURL = try values.decodeIfPresent(String.self, forKey: "return_url")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(permissions, forKey: "permissions")
        try values.encodeIfPresent(returnURL, forKey: "return_url")
    }
}
