// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

/// Payment_method_details_au_becs_debit
public struct PaymentMethodDetailsAuBecsDebit: Codable {
    /// Bank-State-Branch number of the bank account.
    public var bsbNumber: String?
    /// Uniquely identifies this particular bank account. You can use this attribute to check whether two bank accounts are the same.
    public var fingerprint: String?
    /// Last four digits of the bank account number.
    public var last4: String?
    /// ID of the mandate used to make this payment.
    public var mandate: String?

    public init(bsbNumber: String? = nil, fingerprint: String? = nil, last4: String? = nil, mandate: String? = nil) {
        self.bsbNumber = bsbNumber
        self.fingerprint = fingerprint
        self.last4 = last4
        self.mandate = mandate
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.bsbNumber = try values.decodeIfPresent(String.self, forKey: "bsb_number")
        self.fingerprint = try values.decodeIfPresent(String.self, forKey: "fingerprint")
        self.last4 = try values.decodeIfPresent(String.self, forKey: "last4")
        self.mandate = try values.decodeIfPresent(String.self, forKey: "mandate")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(bsbNumber, forKey: "bsb_number")
        try values.encodeIfPresent(fingerprint, forKey: "fingerprint")
        try values.encodeIfPresent(last4, forKey: "last4")
        try values.encodeIfPresent(mandate, forKey: "mandate")
    }
}
