// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct PaymentIntentNextActionWechatPayDisplayQrCode: Codable {
    /// The data being used to generate QR code
    public var data: String
    /// The base64 image data for a pre-generated QR code
    public var imageDataURL: String
    /// The image_url_png string used to render QR code
    public var imageURLPng: String
    /// The image_url_svg string used to render QR code
    public var imageURLSvg: String

    public init(data: String, imageDataURL: String, imageURLPng: String, imageURLSvg: String) {
        self.data = data
        self.imageDataURL = imageDataURL
        self.imageURLPng = imageURLPng
        self.imageURLSvg = imageURLSvg
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.data = try values.decode(String.self, forKey: "data")
        self.imageDataURL = try values.decode(String.self, forKey: "image_data_url")
        self.imageURLPng = try values.decode(String.self, forKey: "image_url_png")
        self.imageURLSvg = try values.decode(String.self, forKey: "image_url_svg")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(data, forKey: "data")
        try values.encode(imageDataURL, forKey: "image_data_url")
        try values.encode(imageURLPng, forKey: "image_url_png")
        try values.encode(imageURLSvg, forKey: "image_url_svg")
    }
}
