// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

/// Payment_method_details_bacs_debit
public struct PaymentMethodDetailsBacsDebit: Codable {
    /// Uniquely identifies this particular bank account. You can use this attribute to check whether two bank accounts are the same.
    public var fingerprint: String?
    /// Last four digits of the bank account number.
    public var last4: String?
    /// ID of the mandate used to make this payment.
    public var mandate: String?
    /// Sort code of the bank account. (e.g., `10-20-30`)
    public var sortCode: String?

    public init(fingerprint: String? = nil, last4: String? = nil, mandate: String? = nil, sortCode: String? = nil) {
        self.fingerprint = fingerprint
        self.last4 = last4
        self.mandate = mandate
        self.sortCode = sortCode
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.fingerprint = try values.decodeIfPresent(String.self, forKey: "fingerprint")
        self.last4 = try values.decodeIfPresent(String.self, forKey: "last4")
        self.mandate = try values.decodeIfPresent(String.self, forKey: "mandate")
        self.sortCode = try values.decodeIfPresent(String.self, forKey: "sort_code")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(fingerprint, forKey: "fingerprint")
        try values.encodeIfPresent(last4, forKey: "last4")
        try values.encodeIfPresent(mandate, forKey: "mandate")
        try values.encodeIfPresent(sortCode, forKey: "sort_code")
    }
}
