// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct PaymentLinksResourceSubscriptionData: Codable {
    /// Integer representing the number of trial period days before the customer is charged for the first time.
    public var trialPeriodDays: Int?

    public init(trialPeriodDays: Int? = nil) {
        self.trialPeriodDays = trialPeriodDays
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.trialPeriodDays = try values.decodeIfPresent(Int.self, forKey: "trial_period_days")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(trialPeriodDays, forKey: "trial_period_days")
    }
}
