// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

/// Payment_method_details_card
public struct PaymentMethodDetailsCard: Codable {
    /// Card brand. Can be `amex`, `diners`, `discover`, `jcb`, `mastercard`, `unionpay`, `visa`, or `unknown`.
    public var brand: String?
    /// Check results by Card networks on Card address and CVC at time of payment.
    public var checks: PaymentMethodDetailsCardChecks?
    /// Two-letter ISO code representing the country of the card. You could use this attribute to get a sense of the international breakdown of cards you've collected.
    public var country: String?
    /// Two-digit number representing the card's expiration month.
    public var expMonth: Int
    /// Four-digit number representing the card's expiration year.
    public var expYear: Int
    /// Uniquely identifies this particular card number. You can use this attribute to check whether two customers who’ve signed up with you are using the same card number, for example. For payment methods that tokenize card information (Apple Pay, Google Pay), the tokenized number might be provided instead of the underlying card number.
    /// 
    /// *Starting May 1, 2021, card fingerprint in India for Connect will change to allow two fingerprints for the same card --- one for India and one for the rest of the world.*
    public var fingerprint: String?
    /// Card funding type. Can be `credit`, `debit`, `prepaid`, or `unknown`.
    public var funding: String?
    /// Installment details for this payment (Mexico only).
    /// 
    /// For more information, see the [installments integration guide](https://stripe.com/docs/payments/installments).
    public var installments: PaymentMethodDetailsCardInstallments?
    /// The last four digits of the card.
    public var last4: String?
    /// ID of the mandate used to make this payment or created by it.
    public var mandate: String?
    /// Identifies which network this charge was processed on. Can be `amex`, `cartes_bancaires`, `diners`, `discover`, `interac`, `jcb`, `mastercard`, `unionpay`, `visa`, or `unknown`.
    public var network: String?
    /// Populated if this transaction used 3D Secure authentication.
    public var threeDSecure: ThreeDSecureDetails?
    /// If this Card is part of a card wallet, this contains the details of the card wallet.
    public var wallet: PaymentMethodDetailsCardWallet?

    public init(brand: String? = nil, checks: PaymentMethodDetailsCardChecks? = nil, country: String? = nil, expMonth: Int, expYear: Int, fingerprint: String? = nil, funding: String? = nil, installments: PaymentMethodDetailsCardInstallments? = nil, last4: String? = nil, mandate: String? = nil, network: String? = nil, threeDSecure: ThreeDSecureDetails? = nil, wallet: PaymentMethodDetailsCardWallet? = nil) {
        self.brand = brand
        self.checks = checks
        self.country = country
        self.expMonth = expMonth
        self.expYear = expYear
        self.fingerprint = fingerprint
        self.funding = funding
        self.installments = installments
        self.last4 = last4
        self.mandate = mandate
        self.network = network
        self.threeDSecure = threeDSecure
        self.wallet = wallet
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.brand = try values.decodeIfPresent(String.self, forKey: "brand")
        self.checks = try values.decodeIfPresent(PaymentMethodDetailsCardChecks.self, forKey: "checks")
        self.country = try values.decodeIfPresent(String.self, forKey: "country")
        self.expMonth = try values.decode(Int.self, forKey: "exp_month")
        self.expYear = try values.decode(Int.self, forKey: "exp_year")
        self.fingerprint = try values.decodeIfPresent(String.self, forKey: "fingerprint")
        self.funding = try values.decodeIfPresent(String.self, forKey: "funding")
        self.installments = try values.decodeIfPresent(PaymentMethodDetailsCardInstallments.self, forKey: "installments")
        self.last4 = try values.decodeIfPresent(String.self, forKey: "last4")
        self.mandate = try values.decodeIfPresent(String.self, forKey: "mandate")
        self.network = try values.decodeIfPresent(String.self, forKey: "network")
        self.threeDSecure = try values.decodeIfPresent(ThreeDSecureDetails.self, forKey: "three_d_secure")
        self.wallet = try values.decodeIfPresent(PaymentMethodDetailsCardWallet.self, forKey: "wallet")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(brand, forKey: "brand")
        try values.encodeIfPresent(checks, forKey: "checks")
        try values.encodeIfPresent(country, forKey: "country")
        try values.encode(expMonth, forKey: "exp_month")
        try values.encode(expYear, forKey: "exp_year")
        try values.encodeIfPresent(fingerprint, forKey: "fingerprint")
        try values.encodeIfPresent(funding, forKey: "funding")
        try values.encodeIfPresent(installments, forKey: "installments")
        try values.encodeIfPresent(last4, forKey: "last4")
        try values.encodeIfPresent(mandate, forKey: "mandate")
        try values.encodeIfPresent(network, forKey: "network")
        try values.encodeIfPresent(threeDSecure, forKey: "three_d_secure")
        try values.encodeIfPresent(wallet, forKey: "wallet")
    }
}
