// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct Period: Codable {
    /// The end date of this usage period. All usage up to and including this point in time is included.
    public var end: Int?
    /// The start date of this usage period. All usage after this point in time is included.
    public var start: Int?

    public init(end: Int? = nil, start: Int? = nil) {
        self.end = end
        self.start = start
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.end = try values.decodeIfPresent(Int.self, forKey: "end")
        self.start = try values.decodeIfPresent(Int.self, forKey: "start")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(end, forKey: "end")
        try values.encodeIfPresent(start, forKey: "start")
    }
}
