// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct SourceTypeEps: Codable {
    public var reference: String?
    public var statementDescriptor: String?

    public init(reference: String? = nil, statementDescriptor: String? = nil) {
        self.reference = reference
        self.statementDescriptor = statementDescriptor
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.reference = try values.decodeIfPresent(String.self, forKey: "reference")
        self.statementDescriptor = try values.decodeIfPresent(String.self, forKey: "statement_descriptor")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(reference, forKey: "reference")
        try values.encodeIfPresent(statementDescriptor, forKey: "statement_descriptor")
    }
}
