// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct SourceMandateNotificationSepaDebitData: Codable {
    /// SEPA creditor ID.
    public var creditorIdentifier: String?
    /// Last 4 digits of the account number associated with the debit.
    public var last4: String?
    /// Mandate reference associated with the debit.
    public var mandateReference: String?

    public init(creditorIdentifier: String? = nil, last4: String? = nil, mandateReference: String? = nil) {
        self.creditorIdentifier = creditorIdentifier
        self.last4 = last4
        self.mandateReference = mandateReference
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.creditorIdentifier = try values.decodeIfPresent(String.self, forKey: "creditor_identifier")
        self.last4 = try values.decodeIfPresent(String.self, forKey: "last4")
        self.mandateReference = try values.decodeIfPresent(String.self, forKey: "mandate_reference")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(creditorIdentifier, forKey: "creditor_identifier")
        try values.encodeIfPresent(last4, forKey: "last4")
        try values.encodeIfPresent(mandateReference, forKey: "mandate_reference")
    }
}
