// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

/// Represents a per-transaction override of a reader configuration
public struct TerminalReaderReaderResourceProcessConfig: Codable {
    /// Override showing a tipping selection screen on this transaction.
    public var isSkipTipping: Bool?

    public init(isSkipTipping: Bool? = nil) {
        self.isSkipTipping = isSkipTipping
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.isSkipTipping = try values.decodeIfPresent(Bool.self, forKey: "skip_tipping")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(isSkipTipping, forKey: "skip_tipping")
    }
}
