// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

/// Represents a line item to be displayed on the reader
public struct TerminalReaderReaderResourceLineItem: Codable {
    /// The amount of the line item. A positive integer in the [smallest currency unit](https://stripe.com/docs/currencies#zero-decimal).
    public var amount: Int
    /// Description of the line item.
    public var description: String
    /// The quantity of the line item.
    public var quantity: Int

    public init(amount: Int, description: String, quantity: Int) {
        self.amount = amount
        self.description = description
        self.quantity = quantity
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.amount = try values.decode(Int.self, forKey: "amount")
        self.description = try values.decode(String.self, forKey: "description")
        self.quantity = try values.decode(Int.self, forKey: "quantity")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(amount, forKey: "amount")
        try values.encode(description, forKey: "description")
        try values.encode(quantity, forKey: "quantity")
    }
}
