// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct TreasuryReceivedCreditsResourceStatusTransitions: Codable {
    /// Timestamp describing when the CreditReversal changed status to `posted`
    public var postedAt: Int?

    public init(postedAt: Int? = nil) {
        self.postedAt = postedAt
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.postedAt = try values.decodeIfPresent(Int.self, forKey: "posted_at")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(postedAt, forKey: "posted_at")
    }
}
