// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct TreasuryInboundTransfersResourceFailureDetails: Codable {
    /// Reason for the failure.
    public var code: Code

    /// Reason for the failure.
    public enum Code: String, Codable, CaseIterable {
        case accountClosed = "account_closed"
        case accountFrozen = "account_frozen"
        case bankAccountRestricted = "bank_account_restricted"
        case bankOwnershipChanged = "bank_ownership_changed"
        case debitNotAuthorized = "debit_not_authorized"
        case incorrectAccountHolderAddress = "incorrect_account_holder_address"
        case incorrectAccountHolderName = "incorrect_account_holder_name"
        case incorrectAccountHolderTaxID = "incorrect_account_holder_tax_id"
        case insufficientFunds = "insufficient_funds"
        case invalidAccountNumber = "invalid_account_number"
        case invalidCurrency = "invalid_currency"
        case noAccount = "no_account"
        case other
    }

    public init(code: Code) {
        self.code = code
    }

    public init(from decoder: Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.code = try values.decode(Code.self, forKey: "code")
    }

    public func encode(to encoder: Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(code, forKey: "code")
    }
}
